behaviors:
  CarMoveToGoal2:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2048
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 264
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.95
        strength: 0.99
      gail:
        strength: 0.3
        demo_path: Demos/EasyDemo0_11.demo
        use_actions: false

    behavioral_cloning:
      demo_path: Demos/EasyDemo0_11.demo
      steps: 750000
      strength: 0.4


    keep_checkpoints: 15
    checkpoint_interval: 1000000
    time_horizon: 64
    max_steps: 50000000
    summary_freq: 100000
    threaded: true
