behaviors:
  CarMoveToGoal2:
    trainer_type: sac
    hyperparameters:
      batch_size: 64
      buffer_size: 50000
      learning_rate: 0.00008
      buffer_init_steps: 0
      tau: 0.008
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.2
      reward_signal_steps_per_update: 10.0

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 50000000
    time_horizon: 500
    summary_freq: 10000
    threaded: true