behaviors:
  CarMoveToGoal2:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 1000000
      learning_rate: 0.0003
      learning_rate_schedule: linear
      
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 50000000
    time_horizon: 64
    summary_freq: 50000
    threaded: true